---
# Commoms role defination for all EC2 instances


#- name: Set SeLinux Permissive
#  shell: setenforce 0
- selinux:
    policy: targeted
    state: permissive

- name: Install common packages
  yum: name={{ item }} state=installed
  with_items:
      - vim
      - unzip
      - wget
